## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import csv

# Import API key
from config import g_key
import csv

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [14]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_Database.csv")

city_data_df

,Unnamed: 0,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ribeira Grande,PT,2022-04-10 19:09:54,38.5167,-28.7000,55.80,71,40,28.77,scattered clouds
1,1,Saint-Philippe,RE,2022-04-10 19:09:54,-21.3585,55.7679,78.39,83,79,13.31,light rain
2,2,Barrow,US,2022-04-10 19:09:55,71.2906,-156.7887,-5.78,77,100,12.66,overcast clouds
3,3,Saint-Pierre,RE,2022-04-10 19:09:55,-21.3393,55.4781,78.48,82,75,21.85,broken clouds
4,4,Bluff,NZ,2022-04-10 19:09:55,-46.6000,168.3333,47.44,86,6,13.29,clear sky
...,...,...,...,...,...,...,...,...,...,...,...
674,674,Paamiut,GL,2022-04-10 19:27:10,61.9940,-49.6678,31.19,79,100,16.31,overcast clouds
675,675,Uvarovo,RU,2022-04-10 19:27:11,51.9849,42.2615,55.18,76,100,7.70,overcast clouds
676,676,Ponta Delgada,PT,2022-04-10 19:23:50,37.7333,-25.6667,57.92,62,20,19.57,few clouds
677,677,Hanna,CA,2022-04-10 19:25:21,51.6334,-111.9018,35.85,32,100,15.99,overcast clouds
678,678,Mana,GF,2022-04-10 19:27:11,5.6592,-53.7767,81.59,75,100,11.99,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

In [5]:
# 4a. Determine if there are any empty rows.

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

    # 6c. Get latitude and longitude from DataFrame

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    

    # 6e. Make request and retrieve the JSON data from the search. 
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.

In [9]:
# 7. Drop the rows where there is no Hotel Name.

In [10]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure